### ISSUE TITLE
[Feature Request]: 有考虑过开发arm的版本吗

### ISSUE THREAD

**Issue by SakuraYuki56** [jxxghp/MoviePilot#1708]
### 当前程序版本

1.72

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望能加一个arm的版本

**Comment by d0zingcat** [comment]
你可以直接通过 docker 自身的功能完成这个需求，通过 **--platform linux/amd64** 这个参数即可。
例如：
`docker run --rm -it --platform linux/amd64 rofrano/vagrant-provider:debian bash`
如果是使用的 docker compose 那么例如：

```
version: "3.8"
services:
  myservice:
    image: myimage:latest
    platform: linux/amd64
    ports:
      - "8080:80"
```
