### ISSUE TITLE
[错误报告]: 配置代理的环境变量会报错

### ISSUE THREAD

**Issue by rehack** [jxxghp/MoviePilot#3015]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

compose配置：
``` yml
services:

    moviepilot:
        stdin_open: true
        tty: true
        container_name: moviepilot-v2
        hostname: moviepilot-v2
        networks:
            - moviepilot
        ports:
            - target: 36521
              published: 36521
              protocol: tcp
        volumes:
            - '/media:/media'
            - '/mnt/docker/moviepilot/v2/config:/config'
            - '/mnt/docker/moviepilot/v2/core:/moviepilot/.cache/ms-playwright'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        environment:
            - 'PROXY_HOST=http://192.168.1.16:7890'
            - 'MOVIEPILOT_AUTO_UPDATE=true'
            - 'NGINX_PORT=36521'
            - 'PORT=36501'
            - 'PUID=0'
            - 'PGID=0'
            - 'UMASK=000'
            - 'TZ=Asia/Shanghai'
            - 'AUTH_SITE=rousi'
            - 'IYUU_SIGN=26xx'
            - 'ROUSI_PASSKEY=xxx'
            - 'SUPERUSER=admin'
            - 'API_TOKEN=xxx'
        restart: always
        image: jxxghp/moviepilot-v2:latest

networks:
  moviepilot:
    name: moviepilot
```
![28331730887661_ pic](https://github.com/user-attachments/assets/44a60698-0ea4-414e-b165-e15e452f6b95)
使用PROXY_HOST代理，启动日志就会出现错误，无法正常启动
另外我的代理http://192.168.1.16:7890是可以正常工作的，旁路由模式
不知道是哪里出了问题
