### ISSUE TITLE
[错误报告]: Docker环境下使用Nginx反代WebUI重启功能未正常生效

### ISSUE THREAD

**Issue by wyxls** [jxxghp/MoviePilot#3731]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.2.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

个人网络环境:
xxx.vip:10000 路由转发端口 -> 总反代`443`端口 -> `192.168.9.11:3000-3001`

通过WebUI操作其他部分功能基本没异常，唯独通过插件触发重启或右上角手动点击重启没有反应，观察了一下docker容器内部的docker_http_proxy.conf，监听的是`38379`，无论是docker后台log还是网页界面都提示
`Error while fetching server API version: 502 Server Error for http://127.0.0.1:38379/version: Bad Gateway`

暂时定位不到问题所在

![WebUI提示](https://github.com/user-attachments/assets/1588c39e-ee8b-4e57-a7d5-81d0903222f0)
![docker log](https://github.com/user-attachments/assets/d602d66e-2ada-4aa3-b834-996ab33490e3)
核心Nginx反代配置:

> location / {
>     proxy_pass http://192.168.9.11:3000;
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
> }

**Comment by cddjr** [comment]
你映射sock没？

**Comment by wyxls** [comment]
按照官方文档的配置，38379是额外放进去的，有没有也会提示error

> version: '3.3'
> services:
>   moviepilot:
>     stdin_open: true
>     tty: true
>     image: registry.zakikun.vip:10000/jxxghp/moviepilot-v2:latest
>     container_name: moviepilot-v2
>     hostname: moviepilot-v2
>     restart: unless-stopped
>     ports:
>       - target: 3000
>         published: 3000
>         protocol: tcp
>       - target: 3001
>         published: 3001
>         protocol: tcp
>       - target: 38379
>         published: 38379
>         protocol: tcp
>     volumes:
>       - '/volume1/medias:/medias'
>       - '/volume1/docker/moviepilot-v2/config:/config'
>       - '/volume1/docker/moviepilot-v2/core:/moviepilot/.cache/ms-playwright'
>       - '/var/run/docker.sock:/var/run/docker.sock:ro'

**Comment by DDSDerek** [comment]
请提供 docker 版本

**Comment by wyxls** [comment]
> 请提供 docker 版本

最上面原文有版本号啊，不过我目前是v2.2.2，问题依然存在

**Comment by DDSDerek** [comment]
> > 请提供 docker 版本
> 
> 最上面原文有版本号啊，不过我目前是v2.2.2，问题依然存在

指的是你的 Docker 版本 `docker --version`

再把你的NAS系统提供一下

**Comment by wyxls** [comment]
> > > 请提供 docker 版本
> > 
> > 
> > 最上面原文有版本号啊，不过我目前是v2.2.2，问题依然存在
> 
> 指的是你的 Docker 版本 `docker --version`
> 
> 再把你的NAS系统提供一下

群晖 DSM 7.2.1-69057 Update 6
Docker version 20.10.23, build 876964a

compose.yaml: 
```
version: '3.3'
services:
  moviepilot:
    stdin_open: true
    tty: true
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot-v2
    hostname: moviepilot-v2
    restart: unless-stopped
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
      - target: 38379
        published: 38379
        protocol: tcp
    volumes:
      - '/volume1/medias:/medias'
      - '/volume1/docker/moviepilot-v2/config:/config'
      - '/volume1/docker/moviepilot-v2/core:/moviepilot/.cache/ms-playwright'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=0
      - PGID=0
      - UMASK=000
      - TZ=Asia/Shanghai
      - PROXY_HOST=http://192.168.9.2:7893
      - HTTP_PROXY=http://192.168.9.2:7893
      - HTTPS_PROXY=http://192.168.9.2:7893
      - AUTH_SITE=hdfans
      - HDFANS_UID=xxxx
      - HDFANS_PASSKEY=yyyyyyyy
    network_mode: bridge

networks:
  bridge:
    external: true
```
